border_radius = 12
shadows = 1
blur = 1
cursor_size = 32

bind = SUPER, Return, spawn, ghostty
bind = SUPER, Q, killclient,
bind = SUPER, M, reload_config
bind = SUPER+SHIFT, M, quit

exec-once = pipewire
exec-once = pipewire-pulse
exec-once = wireplumber
exec-once = nm-applet
