# Keyboard
xkb_rules_layout=no

# keybind
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioLowerVolume,spawn,pamixer --decrease 5
bind=NONE,XF86AudioRaiseVolume,spawn,pamixer --increase 5
bind=NONE,XF86AudioMute,spawn,pactl set-sink-mute @DEFAULT_SINK@ toggle

# TODO: fix this shit
bind=NONE,Print,spawn,flameshot gui
#bind=NONE,Insert,spawn,swaylock
bind=SUPER,Return,spawn,ghostty
bind=SUPER,c,killclient
bind=SUPER,Space,spawn,rofi -show run
bind=SUPER+SHIFT,s,toggleglobal
bind=SUPER,p,spawn,pavucontrol
bind=SUPER,u,spawn,librewolf

# focus windows
bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=SUPER,l,focusdir,right

# move focused window
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right

# scratchpad
#bind=SUPER,z,toggle_named_scratchpad,none,none,ghostty

# layout binds
bind=SUPER,w,setlayout,fair
#bind=SUPER,e,setlayout,scroller
bind=SUPER,Tab,toggleoverview
bind=SUPER,f,togglefullscreen
bind=SUPER+SHIFT,space,togglefloating

# move workspace to another monitor
bind=SUPER+ALT,h,tagmon,left
bind=SUPER+ALT,j,tagmon,down
bind=SUPER+ALT,k,tagmon,up
bind=SUPER+ALT,l,tagmon,right

# tags (prev known as workspaces in i3)
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

bind=SUPER+SHIFT,e,quit
bind=SUPER,r,reload_config

# resize windows
bind=SUPER+CTRL,h,resizewin,-50
bind=SUPER+CTRL,l,resizewin,+50

# focus last window, meaning both app windows and tags for workspaces, TODO: can i make this only go back and forth on workspaces
bind=SUPER,Escape,focuslast
