mouse_accel_profile=0
mouse_natural_scrolling=0


mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Overview mode (Hycov-style — see all windows). Mouse-only in overview:
# In overview, left-click jumps to a window, right-click closes it.
#mousebind=NONE,btn_left,toggleoverview,-1
#mousebind=NONE,btn_right,killclient,0

# swipe throug active workspace with scrooll wheeel fancy :notbad:
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

