mouse_accel_profile=0
mouse_natural_scrolling=0

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

cursor_size=42
#cursor_theme=Adwaita
