# trays
exec-once=nm-applet
exec-once=pasystray
exec-once=slack --startup
exec-once=discord --start-minimized
exec-once=udiskie

# important stuff
exec=dunst
exec=waybar
exec=waypaperd
exec=xdg-desktop-portal-wlr
