# exec=sh $HOME/.dotfiles-nix/home/hx/mango/bg.sh
# don't think i need this when i get waypaperd to work, but we'll leave it here until i figure that out

exec-once=nm-applet
exec-once=pasystray
exec-once=slack --startup
exec-once=discord --start-minimized
# exec-once=dunst
exec-once=waybar
