no_border_when_single=1

windowrule=tags:2,appid:Slack
windowrule=tags:2,appid:discord
windowrule=tags:9,appid:plexamp

# floaters, not the kind you find in your eye, those are the fucking worst
windowrule=isfloating:1,appid:pavucontrol
windowrule=isfloating:1,title:.*pop-up.*
windowrule=isfloating:1,title:.*task_dialog.*
