exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once=nm-applet
exec-once=pasystray
exec-once=slack --startup
exec-once=discord --start-minimized
#exec-once=wpaperd
#exec-once=udiskie
