{
  config,
  pkgs,
  unstable,
  ...
}:

{
  home-manager.users.hx = {
    home.packages = with pkgs; [
      #unstable.telegram-desktop
      #unstable.signal-desktop
      #tor-browser
      #unstable.mumble
      #unstable.slack
      #unstable.plexamp
      wireshark
      #uplex-desktop
      seahorse
      #obsidian
      zathura
      #netflix
      unstable.sublime3
      #librewolf
      unstable.vscode
      #teams-for-linux
      #zotero
      #typst
      #spotify
      #unstable.cider-2
      #sonic-pi
      #xscreensaver
      #inkscape
      #unstable.google-chrome
      #anydesk
      #thunderbird
      #typst
      unstable._1password-gui-beta
      #gajim
    ];
  };
}
